# Generated by Django 2.1.7 on 2019-03-17 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requesttable',
            old_name='text',
            new_name='file',
        ),
        migrations.RemoveField(
            model_name='requesttable',
            name='name',
        ),
        migrations.RemoveField(
            model_name='requesttable',
            name='tick',
        ),
        migrations.AddField(
            model_name='requesttable',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
