# Generated by Django 2.1.7 on 2019-03-17 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_requesttable_antenna'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requesttable',
            name='email',
        ),
        migrations.AddField(
            model_name='requesttable',
            name='user',
            field=models.ForeignKey(default='01', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='requesttable',
            name='antenna',
            field=models.CharField(max_length=20),
        ),
    ]
